/* eslint-disable */
// GENERATED by scripts/build-engine-source.ts — do not edit.
// Source: lib/engine/engine.js + lib/engine/gallery.css

export const ENGINE_JS = `/* ===========================================================================
   Infinite Gallery — engine.

   This is the reference gallery.html engine, ported as-is. The physics, the
   wrap maths, the drift, the inertia (friction 0.93), the entrance stagger,
   the cursor, the filters and the lightbox are unchanged.

   What changed, and only this (§6):
     1. GALLERY is passed in rather than hardcoded.
     2. --accent / --bg come from the gallery record.
     3. object-position is driven per item by --focal.
     4. Videos use posterUrl + the 720p loop in the grid, the 1080p full in the
        lightbox.
     5. SINGLE-PLAY RULE: the block is tiled up to 4×, so a video used to exist
        up to 4 times and all copies played at once. Now only the copy nearest
        the viewport centre plays; the others show their poster. This is a real
        bug in the reference file — iOS Safari silently refuses to decode that
        many streams.
     6. <video> elements are only mounted within one viewport of the visible
        area, and are torn down (decoder released) when they drift outside it.
     7. tile-inner carries an LQIP background so tiles are never flat grey.
     8. Zero media still renders the reference's 40 striped placeholder tiles.
     9. prefers-reduced-motion still disables drift and entrance.
    10. driftSpeed / density multipliers from the gallery record.

   IMPORTANT: this file is the single source of truth for the engine. It is
   imported by the Next app AND inlined verbatim into the static-export HTML by
   scripts/build-engine-source.ts. Keep exactly one top-level \`export function\`
   in it — the generator strips that keyword to inline the file.
   =========================================================================== */

/**
 * @typedef {Object} IGMediaItem
 * @property {string}  [id]
 * @property {'image'|'video'} kind
 * @property {string|null} [gridUrl]
 * @property {string|null} [fullUrl]
 * @property {string|null} [posterUrl]
 * @property {string|null} [fallbackUrl]
 * @property {string|null} [lqip]
 * @property {'s'|'m'|'l'|'xl'} [size]
 * @property {string|null} [tag]
 * @property {string|null} [alt]
 * @property {number} [focalX]
 * @property {number} [focalY]
 *
 * @typedef {Object} IGConfig
 * @property {string}  [title]
 * @property {string}  [tagline]
 * @property {string}  [hint]
 * @property {string}  [accent]
 * @property {string}  [bg]
 * @property {number}  [driftSpeed]
 * @property {number}  [density]
 * @property {boolean} [showFilters]
 * @property {string}  [listHref]
 * @property {IGMediaItem[]} media
 */

/**
 * Mounts the gallery into \`root\`. Returns a teardown function.
 *
 * @param {HTMLElement} root
 * @param {IGConfig} GALLERY
 * @returns {() => void}
 */
function mountGallery(root, GALLERY) {
  'use strict';

  const ac = new AbortController();
  const sig = { signal: ac.signal };
  const $ = (s, r = root) => r.querySelector(s);
  const $$ = (s, r = root) => Array.from(r.querySelectorAll(s));
  const reduce = matchMedia('(prefers-reduced-motion:reduce)').matches;
  const touch = matchMedia('(hover:none)').matches;
  const rand = (a, b) => a + Math.random() * (b - a);
  const esc = (s) =>
    String(s == null ? '' : s).replace(
      /[&<>"']/g,
      (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c],
    );

  /* ---- the 40-slot reference wall, used when a gallery has no media yet ---- */
  const PLACEHOLDERS = [
    ['image', 'l'], ['image', 's'], ['video', 'm'], ['image', 'm'],
    ['image', 'xl'], ['image', 's'], ['video', 'l'], ['image', 'm'],
    ['image', 's'], ['image', 'm'], ['image', 'l'], ['video', 'm'],
    ['image', 's'], ['image', 'xl'], ['image', 'm'], ['image', 's'],
    ['image', 'l'], ['image', 'm'], ['image', 'm'], ['video', 's'],
    ['image', 'l'], ['image', 's'], ['image', 'm'], ['image', 'xl'],
    ['image', 'm'], ['video', 'l'], ['image', 's'], ['image', 'm'],
    ['image', 'l'], ['image', 's'], ['image', 'm'], ['image', 'xl'],
    ['image', 'm'], ['video', 's'], ['image', 'l'], ['image', 'm'],
    ['image', 's'], ['image', 'l'], ['image', 'm'], ['image', 'xl'],
  ].map(([kind, size]) => ({ kind, size, gridUrl: null, fullUrl: null, posterUrl: null }));

  const cfg = GALLERY || { media: [] };
  const M = cfg.media && cfg.media.length ? cfg.media : PLACEHOLDERS;
  const isEmptyState = !(cfg.media && cfg.media.length);

  const driftMul = typeof cfg.driftSpeed === 'number' ? cfg.driftSpeed : 1;
  const densityMul = typeof cfg.density === 'number' ? cfg.density : 1;

  const playSVG = '<svg viewBox="0 0 24 24"><path d="M8 5v14l11-7z"/></svg>';

  /* ---- markup ------------------------------------------------------------ */
  root.classList.add('ig');
  if (cfg.accent) root.style.setProperty('--accent', cfg.accent);
  if (cfg.bg) root.style.setProperty('--bg', cfg.bg);

  root.innerHTML = \`
    \${cfg.listHref ? \`<a class="skip" href="\${esc(cfg.listHref)}">Skip to list view</a>\` : ''}
    <div class="grain"></div>
    <div class="glow"></div>
    <div class="stage" data-stage><div class="board" data-board></div></div>
    <div class="ui">
      <div class="bar">
        <div class="wordmark" data-wordmark>\${esc(cfg.title || 'GALLERY')}<span>\${esc(
          cfg.tagline || 'drag to explore',
        )}</span></div>
        \${
          cfg.showFilters === false
            ? ''
            : \`<div class="filters" data-filters>
                 <button data-f="all" class="active">All</button>
                 <button data-f="image">Photos</button>
                 <button data-f="video">Video</button>
               </div>\`
        }
      </div>
      <div class="hint" data-hint><span class="dot"></span> \${esc(
        cfg.hint || 'Drag, scroll or swipe · it never ends',
      )}</div>
      <div class="count" data-count></div>
    </div>
    <div class="cursor" data-cursor><b data-cursor-label></b></div>
    <div class="lb" data-lb>
      <button class="lb-x" data-lb-x aria-label="Close">&#10005;</button>
      <button class="lb-nav lb-prev" data-lb-prev aria-label="Previous">&#8249;</button>
      <div class="lb-inner" data-lb-inner></div>
      <button class="lb-nav lb-next" data-lb-next aria-label="Next">&#8250;</button>
      <div class="lb-idx" data-lb-idx></div>
    </div>\`;

  const stage = $('[data-stage]');
  const board = $('[data-board]');
  const cursor = $('[data-cursor]');
  const cursorLabel = $('[data-cursor-label]');

  const SIZES = { s: 0.66, m: 0.92, l: 1.18, xl: 1.45 };
  const ASPECTS = [3 / 4, 1, 4 / 3, 16 / 10, 4 / 5, 5 / 4];
  const vw = () => window.innerWidth;
  const vh = () => window.innerHeight;
  const base = () =>
    (touch ? Math.min(vw(), vh()) * 0.4 : Math.min(vw(), vh()) * 0.22) * densityMul;

  /* ---- one repeating block of tiles -------------------------------------- */
  let block = [];
  let BW = 0;
  let BH = 0;

  /**
   * A tile's shape comes from the photo it holds, so object-fit:cover has
   * nothing to crop. The reference picked from a fixed ASPECTS list by cell
   * index, which meant a portrait shot could land in a 16:10 tile and lose most
   * of itself.
   *
   * Clamped, because the wall is a grid of cells: one 3:1 panorama shouldn't be
   * allowed to flatten a whole row. Anything outside the range still crops, but
   * only that item, and only past 2:1. The ASPECTS fallback covers items with no
   * stored dimensions -- placeholders, and anything uploaded before width and
   * height were recorded.
   */
  const MIN_ASPECT = 0.5; // 1:2, taller than 9:16
  const MAX_ASPECT = 2.0; // 2:1, wider than 16:9

  /**
   * Placement is scattered, not gridded. The reference laid tiles out in a
   * cols x rows grid and jittered each one inside its cell, which reads as rows
   * and columns with aisles between them no matter how the cells are shaped --
   * the jitter is bounded by the cell, so the structure always shows through.
   *
   * Instead every tile is dropped at a random position and kept only if it
   * clears the ones already down. That has no preferred axis, so there is no
   * grid to see.
   *
   * DENSITY is the share of the block covered by tiles. Random sequential
   * placement jams short of 1, and measurement puts the ceiling for this size
   * mix around 65%: asking for 0.75 instead of 0.72 buys one extra point of
   * coverage for double the work, because the block just grows until it fits.
   * Aiming slightly above the achievable number is deliberate -- the growth
   * loop then converges down onto it rather than settling early.
   *
   * The whole pack costs ~1-2 ms for 44 tiles, so it runs on every mount and
   * resize without a budget guard.
   */
  const DENSITY = 0.72;
  const GAP = 0.025; // clear space between neighbours, as a fraction of the base unit
  const TRIES = 2000; // random positions attempted per tile
  const GROWTHS = 30; // block enlargements before giving up

  function tileAspect(m, c) {
    const natural = m.width > 0 && m.height > 0 ? m.width / m.height : 0;
    if (!natural) return ASPECTS[(c * 7) % ASPECTS.length];
    return Math.min(MAX_ASPECT, Math.max(MIN_ASPECT, natural));
  }

  /**
   * Overlap test on a torus: the block repeats, so x = 0 and x = BW are the
   * same line. Comparing wrapped centre distances lets a tile straddle the
   * block edge and still be guaranteed not to collide with its neighbour in the
   * next copy -- which is what keeps the seams invisible. A grid never needed
   * this because tiles were trapped inside their cells.
   */
  function clears(a, b, gap, bw, bh) {
    let dx = Math.abs(a.cx - b.cx);
    let dy = Math.abs(a.cy - b.cy);
    if (dx > bw / 2) dx = bw - dx;
    if (dy > bh / 2) dy = bh - dy;
    return dx >= (a.w + b.w) / 2 + gap || dy >= (a.h + b.h) / 2 + gap;
  }

  function pack(order, bw, bh, gap) {
    // A tile wider than half the block could overlap its own wrapped copy, and
    // the centre-distance test can't see that. Grow instead.
    for (const t of order) if (t.w * 2 >= bw || t.h * 2 >= bh) return null;

    const out = [];
    for (const t of order) {
      let seated = false;
      for (let k = 0; k < TRIES && !seated; k++) {
        const cand = { cx: rand(0, bw), cy: rand(0, bh), w: t.w, h: t.h };
        let ok = true;
        for (let i = 0; i < out.length; i++) {
          if (!clears(cand, out[i], gap, bw, bh)) {
            ok = false;
            break;
          }
        }
        if (ok) {
          out.push({ ...t, cx: cand.cx, cy: cand.cy });
          seated = true;
        }
      }
      if (!seated) return null;
    }
    return out;
  }

  function buildBlock() {
    const u = base();
    const n = M.length;
    const gap = u * GAP;

    // Size every tile from its own photo first; where it goes comes after.
    const sized = [];
    for (let i = 0; i < n; i++) {
      const m = M[i];
      const mult = SIZES[m.size] || Object.values(SIZES)[Math.floor(rand(0, 4))];
      const asp = tileAspect(m, i);

      // Size by AREA rather than width. Width-first (what the reference did)
      // gives a portrait tile far more visual weight than a landscape one at
      // the same size key.
      const target = u * mult;
      sized.push({
        mi: i,
        kind: m.kind,
        w: target * Math.sqrt(asp),
        h: target / Math.sqrt(asp),
      });
    }

    // Biggest first. Large tiles have the fewest positions that work, and
    // leaving them until the end is what makes this kind of packing fail.
    const order = sized.slice().sort((a, b) => b.w * b.h - a.w * a.h);
    const tileArea = sized.reduce((s, t) => s + t.w * t.h, 0);
    const aspect = vw() / vh();

    let seated = null;
    for (let g = 0; g < GROWTHS && !seated; g++) {
      const area = (tileArea / DENSITY) * Math.pow(1.025, g);
      const bw = Math.sqrt(area * aspect);
      const bh = area / bw;
      seated = pack(order, bw, bh, gap);
      if (seated) {
        BW = bw;
        BH = bh;
      }
    }

    // Every tile placed at least once, even if the packer never converged --
    // a sparse wall beats a blank one.
    if (!seated) {
      const area = (tileArea / 0.3) * 2;
      BW = Math.sqrt(area * aspect);
      BH = area / BW;
      seated = order.map((t) => ({ ...t, cx: rand(0, BW), cy: rand(0, BH) }));
    }

    block = seated.map((t) => ({
      mi: t.mi,
      kind: t.kind,
      w: t.w,
      h: t.h,
      x: t.cx - t.w / 2,
      y: t.cy - t.h / 2,
    }));

    // Published so the layout can be checked from outside: tiles must not
    // overlap on the torus, and coverage should land near DENSITY.
    board.dataset.blockW = String(Math.round(BW));
    board.dataset.blockH = String(Math.round(BH));
    board.dataset.blockCount = String(block.length);
  }

  /* ---- field: enough block-copies to cover the screen -------------------- */
  let nodes = [];
  let repX = 1;
  let repY = 1;
  let fieldW = 0;
  let fieldH = 0;

  function tileMarkup(m, b) {
    const focal = \`--focal:\${m.focalX == null ? 50 : m.focalX}% \${m.focalY == null ? 50 : m.focalY}%\`;
    const lqip = m.lqip ? \`background-image:url(\${m.lqip});\` : '';
    const label = esc(m.alt || m.tag || '');

    let inner;
    if (m.kind === 'video' && m.gridUrl) {
      // The poster is always in the DOM; the <video> is mounted on top of it
      // only when this copy is near the viewport (§6.6).
      inner = m.posterUrl
        ? \`<img class="media" data-poster src="\${esc(m.posterUrl)}" alt="\${label}" loading="lazy" decoding="async">\`
        : \`<div class="ph">video</div>\`;
      inner += \`<span class="vbadge">\${playSVG}</span>\`;
    } else if (m.kind === 'image' && m.gridUrl) {
      const fb = m.fallbackUrl ? \` onerror="this.onerror=null;this.src='\${esc(m.fallbackUrl)}'"\` : '';
      inner = \`<img class="media" src="\${esc(m.gridUrl)}" alt="\${label}" loading="lazy" decoding="async"\${fb}>\`;
    } else {
      inner = \`<div class="ph">\${b.kind === 'video' ? 'video' : 'photo'} \${String(b.mi + 1).padStart(2, '0')}</div>\`;
    }

    return \`<div class="tile-inner" style="\${focal};\${lqip}">\${inner}\${
      m.tag ? \`<span class="tile-tag">\${esc(m.tag)}</span>\` : ''
    }</div>\`;
  }

  function buildField() {
    dropAllVideos();
    buildBlock();
    repX = Math.ceil(vw() / BW) + 1;
    repY = Math.ceil(vh() / BH) + 1;
    fieldW = repX * BW;
    fieldH = repY * BH;
    board.innerHTML = '';
    nodes = [];
    const frag = document.createDocumentFragment();
    for (let ry = 0; ry < repY; ry++) {
      for (let rx = 0; rx < repX; rx++) {
        for (const b of block) {
          const m = M[b.mi];
          const tile = document.createElement('div');
          tile.className = 'tile';
          tile.style.width = b.w + 'px';
          tile.style.height = b.h + 'px';
          tile.dataset.media = String(b.mi);
          tile.dataset.kind = b.kind;
          tile.innerHTML = tileMarkup(m, b);
          frag.appendChild(tile);
          nodes.push({
            el: tile,
            inner: tile.querySelector('.tile-inner'),
            mi: b.mi,
            baseX: b.x + rx * BW,
            baseY: b.y + ry * BH,
            w: b.w,
            h: b.h,
            kind: b.kind,
            hasVideo: b.kind === 'video' && !!m.gridUrl,
            vid: null,
            _x: 0,
            _y: 0,
          });
        }
      }
    }
    board.appendChild(frag);
    render();
    entrance();
  }

  function entrance() {
    if (reduce) {
      nodes.forEach((nd) => nd.inner.classList.add('in'));
      return;
    }
    nodes.forEach((nd, i) => {
      nd.inner.style.transitionDelay = Math.min(i * 6, 650) + 'ms';
      requestAnimationFrame(() => requestAnimationFrame(() => nd.inner.classList.add('in')));
    });
    setTimeout(() => nodes.forEach((nd) => (nd.inner.style.transitionDelay = '')), 1500);
  }

  /* ---- video mounting + single-play rule --------------------------------- */
  function ensureVideo(nd) {
    if (nd.vid) return;
    const m = M[nd.mi];
    const v = document.createElement('video');
    v.className = 'media';
    v.muted = true;
    v.loop = true;
    v.playsInline = true;
    v.setAttribute('playsinline', '');
    v.setAttribute('muted', '');
    v.preload = 'metadata';
    if (m.posterUrl) v.poster = m.posterUrl;
    v.src = m.gridUrl;
    nd.inner.insertBefore(v, nd.inner.firstChild);
    nd.vid = v;
  }

  function dropVideo(nd) {
    if (!nd.vid) return;
    try {
      nd.vid.pause();
      nd.vid.removeAttribute('src');
      nd.vid.load();
    } catch {
      /* teardown is best-effort */
    }
    nd.vid.remove();
    nd.vid = null;
  }

  function dropAllVideos() {
    for (const nd of nodes) dropVideo(nd);
  }

  /* ---- physics: infinite + idle drift ------------------------------------ */
  let posX = 0;
  let posY = 0;
  let tX = 0;
  let tY = 0;
  let velX = 0;
  let velY = 0;
  let dragging = false;
  let moved = 0;
  let downTile = null;
  let lastX = 0;
  let lastY = 0;
  let lbOpen = false;
  const friction = 0.93;
  const wrap = (v, size) => ((v % size) + size) % size;

  const DRIFT_X = reduce ? 0 : -0.16 * driftMul;
  const DRIFT_Y = reduce ? 0 : -0.09 * driftMul;
  let idle = true;
  let idleT = null;
  function wake() {
    idle = false;
    clearTimeout(idleT);
    idleT = setTimeout(() => {
      idle = true;
    }, 2600);
  }

  let raf = 0;
  function tick() {
    if (!dragging) {
      tX += velX;
      tY += velY;
      velX *= friction;
      velY *= friction;
      if (Math.abs(velX) < 0.01) velX = 0;
      if (Math.abs(velY) < 0.01) velY = 0;
      if (idle && !lbOpen) {
        tX += DRIFT_X;
        tY += DRIFT_Y;
      }
    }
    const e = dragging ? 0.45 : 0.12;
    posX += (tX - posX) * e;
    posY += (tY - posY) * e;
    render();
    raf = requestAnimationFrame(tick);
  }

  let vt = 0;
  function render() {
    if (!fieldW) return;
    for (const nd of nodes) {
      const x = wrap(nd.baseX + posX + BW, fieldW) - BW;
      const y = wrap(nd.baseY + posY + BH, fieldH) - BH;
      nd._x = x;
      nd._y = y;
      nd.el.style.transform = \`translate3d(\${x.toFixed(2)}px,\${y.toFixed(2)}px,0)\`;
    }

    // Visibility bookkeeping every 8th frame, as in the reference.
    if (vt++ % 8 === 0) {
      const W = vw();
      const H = vh();
      const cx = W / 2;
      const cy = H / 2;

      // best[mediaIndex] = the on-screen copy closest to the viewport centre.
      const best = new Map();

      for (const nd of nodes) {
        if (!nd.hasVideo) continue;

        // Mount only within one viewport of the visible area (§6.6).
        const near = nd._x + nd.w > -W && nd._x < 2 * W && nd._y + nd.h > -H && nd._y < 2 * H;
        if (near) ensureVideo(nd);
        else {
          dropVideo(nd);
          continue;
        }

        const onScreen = nd._x + nd.w > 0 && nd._x < W && nd._y + nd.h > 0 && nd._y < H;
        if (!onScreen) continue;

        const dx = nd._x + nd.w / 2 - cx;
        const dy = nd._y + nd.h / 2 - cy;
        const d = dx * dx + dy * dy;
        const prev = best.get(nd.mi);
        if (!prev || d < prev.d) best.set(nd.mi, { nd, d });
      }

      // Single-play rule: exactly one copy of each video plays (§2.3/§6.5).
      for (const nd of nodes) {
        if (!nd.vid) continue;
        const winner = best.get(nd.mi);
        if (winner && winner.nd === nd && !lbOpen) {
          if (nd.vid.paused) nd.vid.play().catch(() => {});
        } else if (!nd.vid.paused) {
          nd.vid.pause();
        }
      }
    }
  }

  /* ---- drag -------------------------------------------------------------- */
  stage.addEventListener(
    'pointerdown',
    (e) => {
      dragging = true;
      moved = 0;
      // Read the tile before setPointerCapture below makes the stage the target
      // of every remaining event for this pointer -- see endDrag.
      downTile = e.target.closest ? e.target.closest('.tile') : null;
      lastX = e.clientX;
      lastY = e.clientY;
      velX = velY = 0;
      wake();
      stage.setPointerCapture(e.pointerId);
      cursor.classList.add('drag');
    },
    sig,
  );

  stage.addEventListener(
    'pointermove',
    (e) => {
      if (!dragging) return;
      const dx = e.clientX - lastX;
      const dy = e.clientY - lastY;
      lastX = e.clientX;
      lastY = e.clientY;
      moved += Math.abs(dx) + Math.abs(dy);
      tX += dx;
      tY += dy;
      velX = dx;
      velY = dy;
    },
    sig,
  );

  function endDrag(e) {
    if (!dragging) return;
    dragging = false;
    cursor.classList.remove('drag');
    wake();
    if (moved < 6) {
      // DIVERGES FROM THE REFERENCE (reference/index.html:350), which reads
      // e.target.closest('.tile') off this pointerup and so can never open the
      // lightbox in a real browser: pointerdown calls stage.setPointerCapture,
      // and the Pointer Events spec retargets every later event for that
      // pointer to the capturing element. e.target here is always the stage,
      // and the stage is a tile's ancestor, so closest() always returns null.
      //
      // The press target is the reliable one -- capture is set inside the
      // pointerdown handler, after that event was already dispatched to the
      // tile. It's also the better semantic: the tile you pressed is the one
      // that opens, even if idle drift slid a different tile under the cursor.
      if (downTile) openLB(+downTile.dataset.media);
    }
    downTile = null;
  }
  stage.addEventListener('pointerup', endDrag, sig);
  stage.addEventListener(
    'pointercancel',
    () => {
      dragging = false;
      downTile = null;
      cursor.classList.remove('drag');
      wake();
    },
    sig,
  );

  /* ---- wheel / trackpad --------------------------------------------------- */
  stage.addEventListener(
    'wheel',
    (e) => {
      e.preventDefault();
      wake();
      tX -= e.deltaX;
      tY -= e.deltaY;
      velX = -e.deltaX * 0.2;
      velY = -e.deltaY * 0.2;
    },
    { passive: false, signal: ac.signal },
  );

  /* ---- custom cursor ------------------------------------------------------ */
  if (!touch) {
    window.addEventListener(
      'pointermove',
      (e) => {
        cursor.style.left = e.clientX + 'px';
        cursor.style.top = e.clientY + 'px';
      },
      { passive: true, signal: ac.signal },
    );
    root.addEventListener(
      'pointerover',
      (e) => {
        if (dragging) return;
        const onTile = e.target.closest('.tile');
        cursor.classList.toggle('ring', !!onTile);
        cursorLabel.textContent = onTile ? 'Open' : '';
      },
      sig,
    );
  }

  /* ---- hint --------------------------------------------------------------- */
  const hint = $('[data-hint]');
  let hidHint = false;
  function hideHint() {
    if (hidHint) return;
    hidHint = true;
    hint.style.opacity = '0';
  }
  stage.addEventListener('pointerdown', hideHint, { once: true, signal: ac.signal });
  stage.addEventListener('wheel', hideHint, { once: true, passive: true, signal: ac.signal });

  /* ---- filters ------------------------------------------------------------ */
  $$('[data-filters] button').forEach((b) => {
    b.addEventListener(
      'click',
      () => {
        $$('[data-filters] button').forEach((x) => x.classList.remove('active'));
        b.classList.add('active');
        const f = b.dataset.f;
        nodes.forEach((nd) => nd.el.classList.toggle('dim', f !== 'all' && nd.kind !== f));
        updateCount(f);
      },
      sig,
    );
  });

  function updateCount(f = 'all') {
    const total = M.length;
    const photos = M.filter((m) => m.kind === 'image').length;
    const vids = total - photos;
    const n = f === 'image' ? photos : f === 'video' ? vids : total;
    $('[data-count]').textContent =
      n + (f === 'video' ? ' videos' : f === 'image' ? ' photos' : ' items');
  }

  /* ---- lightbox ----------------------------------------------------------- */
  const lb = $('[data-lb]');
  const lbInner = $('[data-lb-inner]');
  let cur = 0;

  function openLB(i) {
    cur = i;
    lbOpen = true;
    renderLB();
    lb.classList.add('open');
  }
  function closeLB() {
    lbOpen = false;
    lb.classList.remove('open');
    lbInner.innerHTML = '';
    wake();
  }
  function renderLB() {
    const m = M[cur];
    const src = m && (m.fullUrl || m.gridUrl);
    if (!m || !src) {
      lbInner.innerHTML = \`<div style="font-family:var(--mono);font-size:.8rem;letter-spacing:.15em;color:var(--dim);text-transform:uppercase;padding:60px">\${
        isEmptyState ? 'empty slot &middot; add a ' + (m ? m.kind : 'file') : 'still processing'
      }</div>\`;
    } else if (m.kind === 'video') {
      lbInner.innerHTML =
        \`<video src="\${esc(src)}"\${m.posterUrl ? \` poster="\${esc(m.posterUrl)}"\` : ''} controls autoplay playsinline></video>\` +
        (m.tag ? \`<div class="lb-cap">\${esc(m.tag)}</div>\` : '');
    } else {
      lbInner.innerHTML =
        \`<img src="\${esc(src)}" alt="\${esc(m.alt || m.tag || '')}">\` +
        (m.tag ? \`<div class="lb-cap">\${esc(m.tag)}</div>\` : '');
    }
    $('[data-lb-idx]').textContent =
      String(cur + 1).padStart(2, '0') + ' / ' + String(M.length).padStart(2, '0');
  }
  function stepLB(d) {
    cur = (cur + d + M.length) % M.length;
    renderLB();
  }

  $('[data-lb-x]').addEventListener('click', closeLB, sig);
  $('[data-lb-prev]').addEventListener('click', () => stepLB(-1), sig);
  $('[data-lb-next]').addEventListener('click', () => stepLB(1), sig);
  lb.addEventListener(
    'click',
    (e) => {
      if (e.target === lb) closeLB();
    },
    sig,
  );
  window.addEventListener(
    'keydown',
    (e) => {
      if (!lb.classList.contains('open')) return;
      if (e.key === 'Escape') closeLB();
      if (e.key === 'ArrowRight') stepLB(1);
      if (e.key === 'ArrowLeft') stepLB(-1);
    },
    sig,
  );

  /* ---- resize ------------------------------------------------------------- */
  let rt;
  window.addEventListener(
    'resize',
    () => {
      clearTimeout(rt);
      rt = setTimeout(buildField, 220);
    },
    sig,
  );

  /* ---- go ----------------------------------------------------------------- */
  buildField();
  updateCount();
  raf = requestAnimationFrame(tick);

  return function destroy() {
    ac.abort();
    cancelAnimationFrame(raf);
    clearTimeout(idleT);
    clearTimeout(rt);
    dropAllVideos();
    root.innerHTML = '';
    root.classList.remove('ig');
  };
}
`;

export const ENGINE_CSS = `/* ===========================================================================
   Infinite Gallery — engine stylesheet.

   Ported from the reference gallery.html verbatim. The only changes are:
     · everything is scoped under .ig so it can't leak into the admin UI
     · --focal drives object-position per item (§6.3)
     · .tile-inner carries an LQIP background so tiles are never flat grey (§6.7)
     · .tile-inner > video sits above the poster <img> (§6.4/§6.6)

   Do not restyle. This file is the reference look.
   =========================================================================== */

.ig {
  --bg: #0e0e11;
  --panel: #1a1a1f;
  --text: #eceae4;
  --dim: #7c7a73;
  --line: #26262b;
  --accent: #5a6cff;
  --grotesk: 'Space Grotesk', system-ui, sans-serif;
  --mono: 'Space Mono', ui-monospace, monospace;

  position: fixed;
  inset: 0;
  background: var(--bg);
  color: var(--text);
  font-family: var(--grotesk);
  overflow: hidden;
  -webkit-font-smoothing: antialiased;
  cursor: none;
}

body:has(.ig) {
  margin: 0;
  height: 100%;
  overflow: hidden;
  background: #0e0e11;
}
html:has(.ig) {
  height: 100%;
}

@media (hover: none) {
  .ig {
    cursor: auto;
  }
}

.ig *,
.ig *::before,
.ig *::after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}
.ig img,
.ig video {
  display: block;
  -webkit-user-drag: none;
  user-select: none;
}
.ig ::selection {
  background: var(--accent);
  color: #fff;
}

.ig .grain {
  position: fixed;
  inset: 0;
  z-index: 1;
  pointer-events: none;
  opacity: 0.06;
  mix-blend-mode: screen;
  background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='160' height='160'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='2'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E");
  background-size: 160px;
}

/* soft glow vignette to sink the edges into black */
.ig .glow {
  position: fixed;
  inset: 0;
  z-index: 1;
  pointer-events: none;
  background: radial-gradient(130% 110% at 50% 45%, transparent 50%, rgba(0, 0, 0, 0.6) 100%);
}

/* stage / board */
.ig .stage {
  position: fixed;
  inset: 0;
  z-index: 2;
  overflow: hidden;
  touch-action: none;
}
.ig .board {
  position: absolute;
  top: 0;
  left: 0;
  width: 0;
  height: 0;
}
.ig .tile {
  position: absolute;
  top: 0;
  left: 0;
  will-change: transform;
}
.ig .tile-inner {
  position: relative;
  width: 100%;
  height: 100%;
  overflow: hidden;
  cursor: none;
  background-color: var(--panel);
  background-size: cover;
  background-position: center;
  box-shadow: 0 18px 44px -22px rgba(0, 0, 0, 0.9);
  transition:
    transform 0.55s cubic-bezier(0.16, 1, 0.3, 1),
    box-shadow 0.55s,
    filter 0.55s,
    opacity 0.7s ease;
  transform: scale(1);
  opacity: 0;
}
.ig .tile-inner.in {
  opacity: 1;
}
.ig .tile:hover .tile-inner {
  transform: scale(1.05);
  box-shadow:
    0 30px 60px -26px rgba(0, 0, 0, 1),
    0 0 0 1px color-mix(in srgb, var(--accent) 40%, transparent);
}
.ig .tile:hover {
  z-index: 5;
}
.ig .tile-inner .media {
  width: 100%;
  height: 100%;
  object-fit: cover;
  object-position: var(--focal, 50% 50%);
  filter: saturate(1.02) contrast(1.03) brightness(0.98);
}
/* The <video> is mounted lazily on top of its poster, so swapping it in and
   out never flashes an empty tile. */
.ig .tile-inner video.media {
  position: absolute;
  inset: 0;
  z-index: 2;
}
.ig .dim .tile-inner {
  filter: grayscale(1) brightness(0.5) opacity(0.28);
  pointer-events: none;
}

.ig .tile-tag {
  position: absolute;
  left: 10px;
  bottom: 9px;
  z-index: 3;
  font-family: var(--mono);
  font-size: 0.6rem;
  letter-spacing: 0.12em;
  text-transform: uppercase;
  color: #fff;
  opacity: 0;
  transform: translateY(6px);
  transition:
    opacity 0.4s,
    transform 0.4s;
  text-shadow: 0 1px 6px rgba(0, 0, 0, 0.8);
}
.ig .tile:hover .tile-tag {
  opacity: 1;
  transform: none;
}
.ig .vbadge {
  position: absolute;
  top: 10px;
  right: 10px;
  z-index: 3;
  width: 30px;
  height: 30px;
  border-radius: 50%;
  background: rgba(0, 0, 0, 0.45);
  backdrop-filter: blur(3px);
  display: grid;
  place-items: center;
  border: 1px solid rgba(236, 234, 228, 0.25);
}
.ig .vbadge svg {
  width: 11px;
  height: 11px;
  fill: #fff;
  margin-left: 1px;
}

.ig .ph {
  width: 100%;
  height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  font-family: var(--mono);
  font-size: 0.62rem;
  letter-spacing: 0.2em;
  text-transform: uppercase;
  color: var(--dim);
  background: repeating-linear-gradient(45deg, #191920 0 10px, #15151a 10px 20px);
}

/* fixed UI */
.ig .ui {
  position: fixed;
  inset: 0;
  z-index: 10;
  pointer-events: none;
}
.ig .ui .bar {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  padding: 26px clamp(20px, 4vw, 44px);
}
.ig .wordmark {
  font-family: var(--grotesk);
  font-weight: 700;
  font-size: clamp(1.1rem, 2.4vw, 1.5rem);
  letter-spacing: -0.01em;
  line-height: 1;
}
.ig .wordmark span {
  display: block;
  font-family: var(--mono);
  font-weight: 400;
  font-size: 0.6rem;
  letter-spacing: 0.26em;
  color: var(--dim);
  margin-top: 7px;
  text-transform: uppercase;
}
.ig .filters {
  display: flex;
  gap: 18px;
  pointer-events: auto;
}
.ig .filters button {
  font-family: var(--mono);
  font-size: 0.66rem;
  letter-spacing: 0.18em;
  text-transform: uppercase;
  background: none;
  border: none;
  color: var(--dim);
  cursor: pointer;
  padding: 2px 0;
  position: relative;
}
.ig .filters button::after {
  content: '';
  position: absolute;
  left: 0;
  right: 0;
  bottom: -4px;
  height: 1px;
  background: var(--accent);
  transform: scaleX(0);
  transform-origin: left;
  transition: transform 0.35s;
}
.ig .filters button.active {
  color: var(--text);
}
.ig .filters button.active::after {
  transform: scaleX(1);
}
.ig .hint {
  position: absolute;
  left: 50%;
  bottom: 26px;
  transform: translateX(-50%);
  font-family: var(--mono);
  font-size: 0.64rem;
  letter-spacing: 0.2em;
  text-transform: uppercase;
  color: var(--dim);
  display: flex;
  align-items: center;
  gap: 10px;
  transition: opacity 0.6s;
  white-space: nowrap;
}
.ig .hint .dot {
  width: 5px;
  height: 5px;
  border-radius: 50%;
  background: var(--accent);
  animation: ig-pulse 2.4s ease-in-out infinite;
  box-shadow: 0 0 8px 1px color-mix(in srgb, var(--accent) 70%, transparent);
}
@keyframes ig-pulse {
  0%,
  100% {
    opacity: 0.3;
    transform: scale(0.8);
  }
  50% {
    opacity: 1;
    transform: scale(1.3);
  }
}
.ig .count {
  position: absolute;
  right: clamp(20px, 4vw, 44px);
  bottom: 26px;
  font-family: var(--mono);
  font-size: 0.64rem;
  letter-spacing: 0.18em;
  color: var(--dim);
  text-transform: uppercase;
}

/* custom cursor */
.ig .cursor {
  position: fixed;
  top: 0;
  left: 0;
  z-index: 60;
  width: 9px;
  height: 9px;
  border-radius: 50%;
  background: var(--text);
  pointer-events: none;
  transform: translate(-50%, -50%);
  transition:
    width 0.3s,
    height 0.3s,
    background 0.3s;
  display: grid;
  place-items: center;
  mix-blend-mode: difference;
}
.ig .cursor.ring {
  width: 74px;
  height: 74px;
  background: transparent;
  border: 1px solid var(--text);
}
.ig .cursor.drag {
  width: 54px;
  height: 54px;
  background: rgba(236, 234, 228, 0.12);
  border: 1px solid var(--text);
}
.ig .cursor b {
  font-family: var(--mono);
  font-size: 0.54rem;
  letter-spacing: 0.16em;
  text-transform: uppercase;
  color: var(--text);
  opacity: 0;
  transition: opacity 0.25s;
}
.ig .cursor.ring b {
  opacity: 1;
}
@media (hover: none) {
  .ig .cursor {
    display: none;
  }
}

/* lightbox */
.ig .lb {
  position: fixed;
  inset: 0;
  z-index: 50;
  background: rgba(8, 8, 10, 0.95);
  backdrop-filter: blur(12px);
  display: none;
  align-items: center;
  justify-content: center;
  padding: 6vh 6vw;
  opacity: 0;
  transition: opacity 0.4s;
  cursor: none;
}
.ig .lb.open {
  display: flex;
  opacity: 1;
}
.ig .lb-inner {
  max-width: 1100px;
  max-height: 84vh;
  text-align: center;
  transform: scale(0.96);
  transition: transform 0.45s cubic-bezier(0.16, 1, 0.3, 1);
}
.ig .lb.open .lb-inner {
  transform: scale(1);
}
.ig .lb-inner img,
.ig .lb-inner video {
  max-width: 100%;
  max-height: 78vh;
  box-shadow: 0 40px 100px -30px rgba(0, 0, 0, 1);
}
.ig .lb-cap {
  font-family: var(--mono);
  font-size: 0.66rem;
  letter-spacing: 0.2em;
  text-transform: uppercase;
  color: var(--dim);
  margin-top: 1.2rem;
}
.ig .lb-x {
  position: fixed;
  top: 22px;
  right: 26px;
  width: 44px;
  height: 44px;
  border: 1px solid var(--text);
  border-radius: 50%;
  background: none;
  color: var(--text);
  font-size: 1.1rem;
  cursor: none;
  display: grid;
  place-items: center;
  transition:
    transform 0.35s,
    background 0.3s,
    color 0.3s;
}
.ig .lb-x:hover {
  transform: rotate(90deg);
  background: var(--text);
  color: var(--bg);
}
.ig .lb-nav {
  position: fixed;
  top: 50%;
  transform: translateY(-50%);
  background: none;
  border: none;
  cursor: none;
  color: var(--text);
  font-size: 2rem;
  opacity: 0.45;
  transition: opacity 0.3s;
  padding: 22px;
}
.ig .lb-nav:hover {
  opacity: 1;
}
.ig .lb-prev {
  left: 1vw;
}
.ig .lb-next {
  right: 1vw;
}
.ig .lb-idx {
  position: fixed;
  bottom: 24px;
  left: 50%;
  transform: translateX(-50%);
  font-family: var(--mono);
  font-size: 0.64rem;
  letter-spacing: 0.18em;
  color: var(--dim);
}

.ig :focus-visible {
  outline: 2px solid var(--accent);
  outline-offset: 3px;
}

/* Screen-reader route link, visible only on keyboard focus. */
.ig .skip {
  position: fixed;
  top: 8px;
  left: 8px;
  z-index: 80;
  padding: 10px 14px;
  background: var(--panel);
  color: var(--text);
  font-family: var(--mono);
  font-size: 0.66rem;
  letter-spacing: 0.16em;
  text-transform: uppercase;
  text-decoration: none;
  border: 1px solid var(--line);
  transform: translateY(-200%);
  transition: transform 0.2s;
  pointer-events: auto;
}
.ig .skip:focus {
  transform: none;
}

@media (prefers-reduced-motion: reduce) {
  .ig .hint .dot {
    animation: none;
  }
}
`;
