/**
 * Inlines lib/engine/engine.js + lib/engine/gallery.css into a TypeScript
 * module so the static-export route (§6.10) can emit a genuinely self-contained
 * index.html without reading from disk at runtime (which does not survive
 * Vercel's serverless bundling).
 *
 * Runs automatically on `pnpm dev` and `pnpm build`. The engine has exactly one
 * source of truth: lib/engine/engine.js. This script only strips the `export`
 * keyword so the same code can run as an inline <script>.
 */
import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const ROOT = process.cwd();
const OUT = join(ROOT, 'lib', 'engine', 'generated-source.ts');

function asTemplateLiteral(s: string): string {
  return '`' + s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${') + '`';
}

async function main() {
  const js = await readFile(join(ROOT, 'lib', 'engine', 'engine.js'), 'utf8');
  const css = await readFile(join(ROOT, 'lib', 'engine', 'gallery.css'), 'utf8');

  const exportCount = (js.match(/^export /gm) ?? []).length;
  if (exportCount !== 1) {
    throw new Error(
      `engine.js must have exactly one top-level export (found ${exportCount}) — ` +
        'the inliner strips that keyword to run the file as a plain script.',
    );
  }

  const standalone = js.replace(/^export function/m, 'function');

  const out = `/* eslint-disable */
// GENERATED by scripts/build-engine-source.ts — do not edit.
// Source: lib/engine/engine.js + lib/engine/gallery.css

export const ENGINE_JS = ${asTemplateLiteral(standalone)};

export const ENGINE_CSS = ${asTemplateLiteral(css)};
`;

  await writeFile(OUT, out, 'utf8');
  console.log(
    `  ✓ generated lib/engine/generated-source.ts (${Math.round(js.length / 1024)} KB js, ${Math.round(css.length / 1024)} KB css)`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
